liquidctl/liquidtux

nzxt-kraken3.c

Before we did a dangerous `memcpy` and sent only 2 bytes. I suppose for only 2 commands much better to use the explicit way.

fix init interval for kraken3

---

Kbuild
docs/nzxt-rgb-fan-controller.rst
nzxt-rgb-fan-controller.c

Driver for NZXT "RGB & Fan Controller", Smart Device v2
Currently only one USB ID in id table (the device I have), and no docs.
Works with fancontrol and pwmconfig, no checkpatch.pl issues.
Though I can't verify what happens if fancontrol is enabled on boot because of this issue: https://github.com/lm-sensors/lm-sensors/issues/227 (device names change on every boot, fancontrol always fails to start)

[WIP] nzxt-rgb-fan-controller: add new driver

---

Vagrantfile
tools/vagrant/cd-to-vagrant.yml
tools/vagrant/dev-tools.yml

Creates Fedora 34 VM (from the official image) with debug kernel variant:
$ vagrant up --provider libvirt
$ vagrant ssh
`libvirt` and the default VirtualBox provider are supported.
Inside of the VM:
$ make
$ sudo insmod nzxt-rgb-fan-controller.ko
$ sensors
Supported devices are automatically redirected into the VM on `vagrant up`.
Compared to `virtme`, it doesn't require building a kernel.

Vagrantfile

---

nzxt-smart2.c

/home/runner/work/liquidtux/liquidtux/src/nzxt-smart2.c:713:12: warning: ‘nzxt_smart2_hid_reset_resume’ defined but not used [-Wunused-function]
713 | static int nzxt_smart2_hid_reset_resume(struct hid_device *hdev)
|            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

nzxt-smart2: fix unused-function warning

---

Vagrantfile
nzxt-smart2.c

It is the same device, according to liquidctl sources.
Added in https://github.com/liquidctl/liquidctl/pull/364

nzxt-smart2: add another USB ID

---

nzxt-kraken3.c

Just a one-line fix to correct name initialization for the Z53.
Related: #22

nzxt-kraken3: correct Z53 name initialization

---

nzxt-kraken3.c

Bring fixed duty setting behavior in line with curve point setting - cache the value, but only write to device if the `pwmX_enable` mode is appropriate (in this case, `manual`).

nzxt-kraken3: write fixed duty only if in manual pwmX_enable mode

---

docs/nzxt-kraken3.rst

Add initial kernel doc for the nzxt-kraken3 driver, detailing its expanded capabilities.

nzxt-kraken3: add initial kernel driver docs

---

.github/dependabot.yml

Currently, GitHub Actions in liquidtux repository generates the following warning:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2
```
Dependabot should automatically create a pull request when a major update of an action is available.

Enable Dependabot to update GitHub Actions semi-automatically

---

Vagrantfile

Also, be less paranoid, and trust the official Vagrant box(es), instead of hardcoding download URLs and checksums.

Update Vagrant box to Fedora 37

---

nzxt-kraken3.c

This should resolve the issues noted in #7 and optimize Z series status reporting.
- Values that convert to less than `PUMP_DUTY_MIN` will now be silently set to it without returning error codes
- When setting PWM duty directly, the same value that was set will be reported until the next sensor report interrupt comes through, so that userspace tools will be happ(y/ier)
- I've removed `priv->duty_input` in favor of recording the value in `kraken3_channel_info` for each channel
- Z series don't send the sensor report on their own. Instead of requesting it every time something is read, request it only when the validity interval has passed
- Reformatted code
---
Seems to work when using `fan2go`, here's my config: [fan2go.txt](https://github.com/liquidctl/liquidtux/files/10369233/fan2go.txt). …

nzxt-kraken3: PWM setting fixes; status reporting optimization

---

nzxt-kraken3.c

Was looking through the code and noticed that I didn't remove the spinlock.h include.

nzxt-kraken3: Remove the unused spinlock.h include

---

Makefile

See https://github.com/liquidctl/liquidtux/actions/runs/3955424494/jobs/6773694899#step:6:7
I don't know dash (Ubuntu's /bin/sh) that well, so let's just force Makefile SHELL to be bash.

Makefile: fix shell errors in dkms_install

---

nzxt-kraken3.c

nzxt-kraken3: Mark get_fw_version_cmd as __maybe_unused

---

nzxt-kraken3.c

@amezin noticed in #48 that constant values aren't marked as const. Mark them as such.

nzxt-kraken3: Mark cmd values const

---

nzxt-kraken3.c

I noticed that the comment explaining `STATUS_INTERVAL` is wrong, as per the [liquidctl issue](https://github.com/liquidctl/liquidctl/issues/128#issuecomment-640140272). Fix it.

nzxt-kraken3: Refactor away STATUS_INTERVAL, add explanations

---

nzxt-kraken3.c

This should resolve the issue of fancontrol possibly racing with the first report on X-series devices and reading an `-ENODATA`. Please do roast this approach if something's not right. `completion_done()` will always return true after a `complete_all()` call, that's how we know that the first report has been parsed and to skip doing that again.

nzxt-kraken3: delay reading for X53 until first report is received; ensure proper concurrency for Z53

---

Vagrantfile

This PR adds the missing IDs for NZXT Kraken X53 and Z53 to the Vagrant config.

vagrant: Add missing NZXT Kraken X53 and Z53 product IDs

---

.github/workflows/build.yml
.github/workflows/checkpatch.yml
.github/workflows/dkms.yml

Just noticed that the kernel versions the CI uses are fairly old. Bump them up to current ones, including the Ubuntu version.
---
Shouldn't break anything, I hope? Or should I leave the 5.x ones in and only add these new ones?

ci: Bump Ubuntu and kernel versions for CI builds

---

Vagrantfile

Bump Fedora image version to 39 and fix an undefined method. (Seems like newer Ruby versions got rid of `exists?` in favor of `exist?`).

Fix and update Vagrantfile

---

.github/workflows/build.yml
Makefile

Related to #60. Add W=1 to Makefile.
---
Marking as a draft because I'd like to also add C=1, but I had to install sparse myself, so I need to investigate the Github CI.

Add W=1 to Makefile

---

docs/nzxt-kraken3.rst
nzxt-kraken3.c

This PR:
- improves the things @amezin commented on in #43
- adds a few comments to those parts
- formats the kraken3_raw_event() signature to be on one line
- improves the faultiness logic to return -ENODATA if the device reports it's faulty, for a cycle. Otherwise, stale data would be returned
- notes the faultiness reporting in the docs
- improves lots of things that Guenter complained about in the gigabyte_waterforce driver, that are directly applicable to this one

nzxt-kraken3: Improve things noticed in #43, always return -ENODATA if device is faulty

---

README.md

Update README to note that nzxt-kraken3 will be available starting with Linux 6.9; note support for Kraken Z series devices.
While at it, fix flow of a sentence.
Closes #21, closes #7.

Update README since nzxt-kraken3 is now mainlined

---

README.md
docs/nzxt-kraken3.rst
nzxt-kraken3.c

Looking at https://github.com/liquidctl/liquidctl/pull/605, seems like the write commands being different is pretty much all that has to be covered (?)

nzxt-kraken3: Add support for NZXT Kraken 2023 (normal and elite) models

---

nzxt-kraken3.c

Was preparing patches and noticed I didn't add these new models to the header comment.

nzxt-kraken3: Note 2023/2023 Elite models in header comment

---

README.md

#67 is in for 6.10, note in README.

readme: Note that NZXT Kraken 2023 support is in Linux 6.10

---

drivers/hwmon/nzxt-smart2.c

From hwmon-next: https://git.kernel.org/pub/scm/linux/kernel/git/groeck/linux-staging.git/commit/?h=hwmon-next&id=246e6426a87ee4dbb8cd08c9b43323263b5ab76f

nzxt-smart2: Add USB ID 1e71:2020

---

drivers/hwmon/nzxt-grid3.c
drivers/hwmon/nzxt-kraken2.c
drivers/hwmon/nzxt-kraken3.c
drivers/hwmon/nzxt-smart2.c

This will fix the compilation errors shown in recent kernel sources caused by the relocation of asm/unaligned.h to its new location at linux/unaligned.h

fixes asm/unaligned.h related compile errors
